supervisor:
  port: 50000
  health_check_interval: 10s
  heartbeat_timeout: 30s
  shutdown_timeout: 60s

license:
  distribution: "open-source"

database:
  name: redb

logging:
  level: info
  retention_days: 7
  max_size_mb: 1024

services:
  # Core Services
  security:
    enabled: true
    required: true
    executable: ./bin/redb-security
    args:
      - --port=50051
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: security

  unifiedmodel:
    enabled: true
    required: true
    executable: ./bin/redb-unifiedmodel
    args:
      - --port=50052
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: unifiedmodel

  webhook:
    enabled: true
    required: true
    executable: ./bin/redb-webhook
    args:
      - --port=50053
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: webhook

  # Data Services
  transformation:
    enabled: true
    required: true
    executable: ./bin/redb-transformation
    args:
      - --port=50054
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: transformation
    resources:
      max_memory_mb: 2048
      max_cpu_percent: 100

  core:
    enabled: true
    required: true
    executable: ./bin/redb-core
    args:
      - --port=50055
      - --supervisor=localhost:50000
    dependencies:
      - security
      - webhook
      - unifiedmodel
      - transformation
    environment:
      SERVICE_NAME: core

  mesh:
    enabled: true
    required: true
    executable: ./bin/redb-mesh
    args:
      - --port=50056
      - --supervisor=localhost:50000
    dependencies:
      - core
    environment:
      SERVICE_NAME: mesh
    external_port: 8443

  anchor:
    enabled: true
    required: true
    executable: ./bin/redb-anchor
    args:
      - --port=50057
      - --supervisor=localhost:50000
    dependencies:
      - core
      - mesh
    environment:
      SERVICE_NAME: anchor

  # API Services
  integration:
    enabled: true
    required: true
    executable: ./bin/redb-integration
    args:
      - --port=50058
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: integration
    dependencies:
      - core
    resources:
      max_memory_mb: 2048
      max_cpu_percent: 100

  clientapi:
    enabled: true
    required: true
    executable: ./bin/redb-clientapi
    args:
      - --port=50059
      - --supervisor=localhost:50000
    dependencies:
      - core
    environment:
      SERVICE_NAME: clientapi
    external_port: 8080

  mcpserver:
    enabled: true
    required: true
    executable: ./bin/redb-mcpserver
    args:
      - --port=50060
      - --supervisor=localhost:50000
    dependencies:
      - core
    environment:
      SERVICE_NAME: mcpserver