supervisor:
  port: 50000
  health_check_interval: 10s
  heartbeat_timeout: 30s
  shutdown_timeout: 60s

license:
  distribution: "open-source"

# Global configuration for the reDB system
global:
  multi_tenancy:
    # Mode: "single-tenant" for open-source version, "multi-tenant" for enterprise
    mode: "single-tenant"
    # Default tenant settings for single-tenant mode
    default_tenant_id: "default-tenant"
    default_tenant_name: "Default Tenant"
    default_tenant_url: "default"

# Keyring configuration for storing secrets
keyring:
  # Backend: "auto" (try system first, fallback to file), "system", or "file"
  backend: "file"
  # Path for file-based keyring (optional, uses default if not specified)
  # path: "/custom/path/to/keyring.json"
  # Master key for file-based keyring encryption (use REDB_KEYRING_PASSWORD env var in production)
  # master_key: "your-secure-master-key"
  # Service name prefix for system keyring entries
  service_name: "redb"

# Instance group configuration for running multiple instances on the same machine
instance_group:
  # Unique identifier for this instance group (change for each instance)
  group_id: "instance2"
  # Port offset to avoid conflicts (0 = no offset, 1000 = add 1000 to all ports)
  port_offset: 1000

# Internal PostgreSQL database configuration
database:
  # Database name
  name: redb

logging:
  level: info
  retention_days: 7
  max_size_mb: 1024

services:
  # Core Services
  security:
    enabled: true
    required: true
    executable: ./redb-security
    args:
      - --port=50051
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: security

  unifiedmodel:
    enabled: true
    required: true
    executable: ./redb-unifiedmodel
    args:
      - --port=50052
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: unifiedmodel

  webhook:
    enabled: true
    required: true
    executable: ./redb-webhook
    args:
      - --port=50053
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: webhook

  # Data Services
  transformation:
    enabled: true
    required: true
    executable: ./redb-transformation
    args:
      - --port=50054
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: transformation
    resources:
      max_memory_mb: 2048
      max_cpu_percent: 100

  mesh:
    enabled: true
    required: true
    executable: ./redb-mesh
    args:
      - --grpc-bind=127.0.0.1:50056
      - --enable-grpc
      - --listen=0.0.0.0:10001
      - --supervisor=localhost:50000
      - --config=config_instance2.yaml
    dependencies:
      - security
      - webhook
      - unifiedmodel
      - transformation
    environment:
      SERVICE_NAME: mesh
    config:
      services.mesh.external_port: "10001"
      services.mesh.timeout: "30"
      services.mesh.mesh_id: "default-mesh"
      services.mesh.node_id: "1001"
      services.mesh.mesh_token: ""
      services.mesh.tls.enabled: "true"
      services.mesh.tls.cert_file: "./node-1001-cert.pem"
      services.mesh.tls.key_file: "./node-1001-key.pem"
      services.mesh.tls.ca_file: "./mesh-ca-cert.pem"

  core:
    enabled: true
    required: true
    executable: ./redb-core
    args:
      - --port=50055
      - --supervisor=localhost:50000
    dependencies:
      - mesh
    environment:
      SERVICE_NAME: core

  anchor:
    enabled: true
    required: true
    executable: ./redb-anchor
    args:
      - --port=50057
      - --supervisor=localhost:50000
    dependencies:
      - core
      - mesh
    environment:
      SERVICE_NAME: anchor

  # API Services
  integration:
    enabled: true
    required: true
    executable: ./redb-integration
    args:
      - --port=50058
      - --supervisor=localhost:50000
    environment:
      SERVICE_NAME: integration
    dependencies:
      - core
    resources:
      max_memory_mb: 2048
      max_cpu_percent: 100

  clientapi:
    enabled: true
    required: true
    executable: ./redb-clientapi
    args:
      - --port=50059
      - --supervisor=localhost:50000
    dependencies:
      - core
    environment:
      SERVICE_NAME: clientapi
  
  mcpserver:
    enabled: true
    required: true
    executable: ./redb-mcpserver
    args:
      - --port=50060
      - --supervisor=localhost:50000
    dependencies:
      - core
    environment:
      SERVICE_NAME: mcpserver
